version: '2'
services:
 etcd:
  command: "-name etcd0 -advertise-client-urls http://etcd:2379,http://etcd:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls http://etcd:2380 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster-1 -initial-cluster etcd0=http://etcd:2380"
  image: quay.io/coreos/etcd:v2.0.8
  container_name: etcd
  ports:
  - "4001:4001"
  - "2380:2380"
  - "2379:2379"

 registrator:
  command: "-internal=true etcd://etcd:2379"
  image: gliderlabs/registrator:latest
  container_name: registrator
  links:
  - etcd
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
 
 lolek:
  image: nazman/lolek
  ports:
  - "80"
  
 bolek:
  image: nazman/bolek
  ports:
  - "80"
  
 nginx-confd:
  build: ./docker-nginx-confd
  links:
  - etcd
  container_name: nginx-confd
  ports:
  - "8080:80"
  environment:
   - CONFD_BACKEND=etcd
   - ETCD_HOST=etcd
   - ETCD_PORT=4001
  
  
  
