[template]
src = "nginx.conf.tmpl"
dest = "/etc/nginx/conf.d/services.conf"
owner = "root"
mode = "0644"
keys = [
  "/lolek",
  "/bolek"
]
check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "/usr/sbin/service nginx reload"